### PR TITLE
Fix handling of extraneous output in simctl list.

### LINKED ISSUE #10213: CocoaPods not parsing simctl output, results in error
When I try a `pod lib lint` I'm receiving an error:
`    - ERROR | [iOS] unknown: Encountered an unknown error (784: unexpected token at '2020-11-17 12:11:19.652 simctl[48241:1246091] apply_selection_policy_once: prefer use of removable GPUs (via com.apple.CoreSimulator.simctl:GPUSelectionPolicy->preferRemovable)`

I have an eGPU attached to my machine which causes additional logs to come back. 
For example:

`xcrun simctl list`will return:
```
xcrun simctl list
2020-11-17 12:19:37.295 simctl[53441:1264174] apply_selection_policy_once: prefer use of removable GPUs (via com.apple.CoreSimulator.simctl:GPUSelectionPolicy->preferRemovable)
== Device Types ==
```

I think that the cause might be `lib/cocoapods/simctl.rb` (and I suppose others where parsing occurs) failing to parse this output correctly.

I'm using CocoaPods 1.10.0 on macOS 11.0.1.

### PR DESCRIPTION
**Pull request by dnkoutso**
closes https://github.com/CocoaPods/CocoaPods/issues/10213

### CODE REVIEW

File: lib/fourflusher/find.rb [hunk 1]
```diff
@@ -93,6 +93,11 @@ def initialize(device_json, os_name, os_version)
 
   # Executes `simctl` commands
   class SimControl
+    LINES_TO_REMOVE = [
+      'Install Started',
+      'Install Succeeded'
```
Comment (amorde) [inline lib/fourflusher/find.rb:98]: I wonder if there's an `Install Failed` 🤔

**Review by amorde — APPROVED** [review]

File: lib/fourflusher/find.rb (hunk 1 above)
Comment (dnkoutso) [reply lib/fourflusher/find.rb]: added it anyway!
